shish/rosettaboy

cpp/CMakeLists.txt

You should rerun benchmark after that

Gotta go fast

---

py/src/errors.py
py/src/main.py

Not 100 percent sure if this is right. Do let me know if there's anything wrong or to be improved on so I can make the appropriate changes

Preliminary changes to python error handling

---

cpp/src/cpu.cpp
cpp/src/cpu.h
go/README.md
go/src/cpu.go
nim/src/cpu.nim
php/src/cart.php
php/src/consts.php
php/src/cpu.php
php/src/gpu.php
py/src/cpu.py
rs/src/cpu.rs
zig/src/cpu.zig

* __->__ #47
deduplicate check_interrupt

deduplicate check_interrupt

---

utils/cpudiff.py

* __->__ #54
[utils] have CPU diff vary amount of history it shows

[utils] have CPU diff vary amount of history it shows

---

zig/run_safe.sh
zig/src/cpu.zig
zig/src/gpu.zig

* __->__ #51
[zig] GPU progress, see #44

[zig] GPU progress, see #44

---

rs/src/cpu.rs

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/35).
* __->__ #35
[rs] bitflags for CPU Flag register
an experiment

[rs] bitflags for CPU Flag register

---

cpp/src/buttons.cpp
go/src/buttons.go
nim/src/buttons.nim
php/src/buttons.php
py/src/buttons.py
rs/src/buttons.rs
zig/src/buttons.zig

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/59).
* __->__ #59
[all] specifically ignore the top two bits in JOYP

[all] specifically ignore the top two bits in JOYP

---

cpp/src/cpu.cpp
cpp/src/cpu.h
go/src/cpu.go
nim/src/cpu.nim
php/src/cpu.php
rs/src/cpu.rs
zig/src/cpu.zig

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/60).
* __->__ #60
[all] load opargs at the same time as loading ops

[all] load opargs at the same time as loading ops

---

cpp/src/cpu.cpp
go/src/cpu.go
nim/src/cpu.nim
php/src/cpu.php
rs/src/cpu.rs
zig/src/cpu.zig

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/61).
* __->__ #61
[all] pc consistency

[all] pc consistency

---

utils/format-all.sh

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/62).
* __->__ #62
[utils] bash rather than sh

[utils] bash rather than sh

---

utils/cpudiff.py

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/63).
* __->__ #63
[utils] also start cpudiff'ing if we see ram

[utils] also start cpudiff'ing if we see ram

---

cpp/src/cpu.cpp
go/src/cpu.go
nim/src/cpu.nim
php/src/cpu.php
rs/src/cpu.rs
zig/src/cpu.zig

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/64).
* __->__ #64
[all] make dump_regs access ram in the same order

[all] make dump_regs access ram in the same order

---

rs/src/cpu.rs

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/66).
* __->__ #66
[rs] get arg from pc+1

[rs] get arg from pc+1

---

zig/src/cpu.zig

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/68).
* __->__ #68
[zig] get arg from pc+1

[zig] get arg from pc+1

---

php/src/ram.php

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/65).
* __->__ #65
[php] wrap on _inc()

[php] wrap on _inc()

---

cpp/src/gpu.cpp
go/src/gpu.go
nim/src/gpu.nim
php/src/gpu.php
py/src/gpu.py
rs/src/gpu.rs
zig/src/gpu.zig

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/67).
* __->__ #67
[all] consistent use of stat, and avoid ram access

[all] consistent use of stat, and avoid ram access

---

go/src/buttons.go
go/src/cpu.go

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/70).
* __->__ #70
[go] use ram get/set for buttons

[go] use ram get/set for buttons

---

py/format.sh
py/run.sh
py/src/cpu.py

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/36).
* __->__ #36
[py] try using match, like the other implementations

[py] try using match, like the other implementations

---

utils/trace-all.sh

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/75).
* __->__ #75
[utils] script for tracing to compare CPU logs

[utils] script for tracing to compare CPU logs

---

cpp/src/cpu.cpp
cpp/src/ram.h
go/src/cpu.go
go/src/ram.go
nim/src/cpu.nim
nim/src/ram.nim
php/src/cpu.php
php/src/main.php
php/src/ram.php
rs/src/cpu.rs
rs/src/ram.rs
zig/src/cpu.zig
zig/src/ram.zig

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/76).
* __->__ #76
[all] inline single-use ram functions

[all] inline single-use ram functions

---

py/src/buttons.py
py/src/cart.py
py/src/consts.py
py/src/cpu.py
py/src/gpu.py
py/src/ram.py

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/79).
* __->__ #79
[py] mark static enums as Final, see #78

[py] mark static enums as Final, see #78

---

py/src/args.py
py/src/clock.py
py/src/cpu.py
py/src/errors.py
py/src/gameboy.py
py/src/gpu.py

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/80).
* __->__ #80
[py] pass mypy --strict checks, see #78

[py] pass mypy --strict checks, see #78

---

py/.gitignore
py/.pyre_configuration
py/src/cpu.py
py/src/gpu.py

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/86).
* __->__ #86
[py] better typing, fixes #83

[py] better typing, fixes #83

---

.github/workflows/pxd.yml

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/88).
* __->__ #88
[pxd] github workflow

[pxd] github workflow

---

.github/templates/build/action.yml
.github/templates/format/action.yml
.github/workflows/cpp.yml
.github/workflows/go.yml
.github/workflows/nim.yml
.github/workflows/php.yml
.github/workflows/pxd.yml
.github/workflows/py.yml
.github/workflows/rs.yml
.github/workflows/zig.yml

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/84).
* __->__ #84
[all] attempt at templating github actions

[all] attempt at templating github actions

---

.github/templates/build/action.yml
.github/templates/format/action.yml
.github/templates/nix/action.yml
.github/workflows/cpp.yml
.github/workflows/go.yml
.github/workflows/nim.yml
.github/workflows/php.yml
.github/workflows/pxd.yml
.github/workflows/py.yml
.github/workflows/rs.yml
.github/workflows/zig.yml

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/82).
* __->__ #82
[all][wip] test nix on github

[all][wip] test nix on github

---

.github/workflows/common.yml

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/92).
* __->__ #92
[all] combine caches

[all] combine caches

---

py/format.sh

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/91).
* __->__ #91
[py] check type hints as part of formatting

[py] check type hints as part of formatting

---

.github/workflows/cpp.yml
cpp/run.sh
cpp/shell.nix
pxd/py_env.sh
pxd/shell.nix
py/py_env.sh
py/shell.nix

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/93).
* __->__ #93
[cpp/py/pxd] cache based on OS+arch rather than hostname

[cpp/py/pxd] cache based on OS+arch rather than hostname

---

.github/workflows/common.yml
.github/workflows/cpp.yml
.github/workflows/go.yml
.github/workflows/nim.yml
.github/workflows/php.yml
.github/workflows/pxd.yml
.github/workflows/py.yml
.github/workflows/rs.yml
.github/workflows/zig.yml

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/94).
* __->__ #94
[all] cache apt packages

[all] cache apt packages

---

pxd/setup.py

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/95).
* __->__ #95
[pxd] multi-threaded build is sometimes broken

[pxd] multi-threaded build is sometimes broken

---

py/src/buttons.py
py/src/cart.py
py/src/clock.py
py/src/cpu.py
py/src/errors.py
py/src/gameboy.py
py/src/gpu.py
py/src/main.py
py/src/ram.py

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/96).
* #97
* __->__ #96
[py] absolute imports

[py] absolute imports

---

py/.gitignore
py/src/cart.py
py/src/errors.py
py/src/main.py

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/97).
* __->__ #97
[py] mypyc compatibility

[py] mypyc compatibility

---

.github/workflows/common.yml
.github/workflows/php.yml
php/format.sh

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/98).
* __->__ #98
[php] format setup in format.sh

[php] format setup in format.sh

---

README.md

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/100).
* __->__ #100
benchmark updates

benchmark updates

---

README.md
cpp/build.sh
cpp/build_debug.sh
nim/.gitignore
nim/build.sh
nim/build_debug.sh
nim/build_speed.sh
php/build.sh
php/build_opcache.sh
pxd/build.sh
py/build.sh
py/build_mypyc.sh
py/py_env.sh
rs/build_debug.sh
rs/build_lto.sh
zig/build.sh
zig/build_safe.sh

Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/101).
* __->__ #101
[all] make location-independent binaries

[all] make location-independent binaries

---

nim/build_speed.sh
nim/shell.nix

* __->__ #102
[nim] nix helps with lld

[nim] nix helps with lld

---

py/build_mypyc.sh

* __->__ #103
[py] maybe cross-platform sed

[py] maybe cross-platform sed

---

.github/workflows/common.yml
README.md
cpp/CMakeLists.txt
cpp/build_lto.sh

[cpp] LTO build

---

php/shell.nix
utils/Dockerfile

If you don't want to pin it, can change:
```nix
{
src = builtins.fetchTarball "https://github.com/shish/php-sdl/archive/refs/heads/master.tar.gz";
}
```
Or jump on the flake train and let `nix flake update` handle it :P

[php/nix] pull in sdl ext

---

php/src/gameboy.php
php/src/gpu.php

* __->__ #110
Specify more class variables, based on @jbboehr's branch

Specify more class variables, based on @jbboehr's branch

---

utils/Dockerfile

* __->__ #112
also add python-dev for cython builds

also add python-dev for cython builds

---

php/.phpstan.neon
php/composer.json
php/composer.lock
php/format.sh
php/src/apu.php
php/src/buttons.php
php/src/cart.php
php/src/cpu.php
php/src/errors.php
php/src/gameboy.php
php/src/gpu.php

phpstan for php

---

py/py_env.sh

* __->__ #122
Install mypy>=1.0.0 rather than git HEAD, see #121

Install mypy>=1.0.0 rather than git HEAD, see #121

---

php/composer.json
php/composer.lock
php/shell.nix
php/src/args.php
php/src/gameboy.php
php/src/main.php

Could use a library like symfony console but this is probably fine too

[php] improved argument parsing

---

zig/shell.nix

I believe the key missing ingredient is `pkg-config`. Additionally, the shell can be simplified.

[zig/nix] simplify zig/shell.nix

---

cpp/CMakeLists.txt

* __->__ #129
[cpp] make CMakeLists nice, like the C version

[cpp] make CMakeLists nice, like the C version

---

zig/build_safe.sh

* __->__ #132
[zig] fix build-safe with 0.11

[zig] fix build-safe with 0.11

---

py/src/gpu.py

* __->__ #133
avoid star import

avoid star import

---

c/CMakeLists.txt

* __->__ #130
[c] Comment out broken shared library, for now

[c] Comment out broken shared library, for now

---

nim/shell.nix

[nim] llvm 15

---

nim/build_lto.sh

release+lto could be interesting too because "danger" gives some boost, but also disable some checks - it is not default choose in many cases, but release+lto is always ok

[nim] +release-lto

---

rs/src/apu.rs
rs/src/cpu.rs

[rs] s/overflowing/wrapping/

---

.github/workflows/zig.yml
zig/src/cart.zig
zig/src/clock.zig
zig/src/cpu.zig
zig/src/gpu.zig

[zig] format
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/shish/rosettaboy/pull/140).
* __->__ #140
* #139

[zig] format

---

rs/build.sh
rs/build_debug.sh
rs/build_lto.sh

[rs] consistentify build scripts

[rs] consistentify build scripts

---

zig/src/args.zig

[zig] --version
```
$ ./build.sh && ./rosettaboy-release --version
0.11.0 ReleaseFast stage2_llvm
```

[zig] --version

---

nim/src/args.nim

[nim] --version
(Can't test yet because nim building is broken on my laptop...)

[nim] --version

---

go/src/args.go

[go] -version
```
$ ./rosettaboy-release -version
go1.20.8
```

[go] -version

---

all.py

[all] all.py version command

---

c/src/args.c

[c] --version
```
$ ./rosettaboy-release --version
Apple LLVM 15.0.0 (clang-1500.0.40.1)
```

[c] --version

---

cpp/src/args.cpp

[cpp] --version
```
$ ./rosettaboy-release --version
Apple LLVM 15.0.0 (clang-1500.0.40.1)
```

[cpp] --version

---

py/py_env.sh
py/src/args.py
py/src/main.py

[py] --version

---

php/src/args.php
php/src/main.php

[php] --version
```
$ ./build.sh && ./rosettaboy-release --version 2>/dev/null
8.2.10
```

[php] --version

---

pxd/py_env.sh
pxd/src/args.py

[pxd] --version
(Can't test because building is broken on my laptop)

[pxd] --version

---

all.py

[utils] crash less on corrupt binaries

[utils] crash less on corrupt binaries

---

utils/Dockerfile

[utils] sudo-able docker image

[utils] sudo-able docker image

---

c/src/ram.c

[c] make sure fread() return is checked

[c] make sure fread() return is checked

---

pxd/src/gpu.py

[pxd] format

---

.github/workflows/common.yml

[ci] bump github actions

---

rs/build_cranelift_debug.sh
utils/Dockerfile

[rs] add cranelift compiler

---

c/build_clang.sh

[c] add clang build

---

.devcontainer/devcontainer.json

[dev] add devcontainer config

---

rs/src/buttons.rs
rs/src/consts.rs
rs/src/cpu.rs
rs/src/gpu.rs
rs/src/main.rs

[rs] use bitflags in each module

[rs] use bitflags in each module

---

.github/workflows/utils.yml

[ci] bumps

---

utils/Dockerfile

[nim] fix arm install

---

.github/workflows/utils.yml
utils/Dockerfile

[all] staged docker build

---

utils/Dockerfile

[docker] updates

---

rs/Cargo.lock
rs/Cargo.toml
rs/src/consts.rs
rs/src/cpu.rs

[rs] bumps

---

c/build.sh
c/build_debug.sh
c/build_lto.sh

[c] BUILD_ROOT environment var to minimise pollution in the source repo

[c] BUILD_ROOT environment var to minimise pollution in the source repo

---

cpp/build.sh
cpp/build_debug.sh
cpp/build_lto.sh

[cpp] BUILD_ROOT environment var to minimise pollution in the source repo

[cpp] BUILD_ROOT environment var to minimise pollution in the source repo

---

rs/build.sh
rs/build_cranelift_debug.sh
rs/build_debug.sh
rs/build_lto.sh

[rs] BUILD_ROOT environment var to minimise pollution in the source repo

[rs] BUILD_ROOT environment var to minimise pollution in the source repo

---

all.py

[all.py] ignore rosettaboy.nimble
[many] BUILD_ROOT environment var to minimise pollution in the source repo

[all.py] ignore rosettaboy.nimble

---

.github/workflows/pxd.yml
.github/workflows/py.yml

[py/pxy] system black

---

rs/Cargo.lock
rs/Cargo.toml
rs/README.md
rs/benches/scratch.rs
rs/src/lib.rs

[rs] try benchmark with divan

---

.docker/zig.dockerfile
.github/workflows/devkit-zig.yml

[devkits] zig devkit

---

.docker/go.dockerfile
.github/workflows/devkit-go.yml

[devkit] go devkit

---

.docker/rust.dockerfile
.github/workflows/devkit-rust.yml

[devkits] rust devkit

---

.docker/nim.dockerfile
.github/workflows/devkit-nim.yml
.github/workflows/devkit.yml

[devkits] nim devkit

---

.github/workflows/devkit-python.yml

[devkit] build python 3.12

---

py/build_pypy.sh

[py] add pypy
